// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd56RxMS8hJcLRFTefExF127lKuJDkVEc',
    appId: '1:853841975905:web:6c196ac96cc82b1a4ae820',
    messagingSenderId: '853841975905',
    projectId: 'vybely-chat-app',
    authDomain: 'vybely-chat-app.firebaseapp.com',
    storageBucket: 'vybely-chat-app.firebasestorage.app',
    measurementId: 'G-ELMN94VVZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGiBMc1X-nj94L2fCnwCeMHxCcZrcLuLs',
    appId: '1:853841975905:android:afa96c6db07800a54ae820',
    messagingSenderId: '853841975905',
    projectId: 'vybely-chat-app',
    storageBucket: 'vybely-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6QplcgEeW0MyTfgdNl64V9I6VreL9gg',
    appId: '1:853841975905:ios:e064db5fa395292e4ae820',
    messagingSenderId: '853841975905',
    projectId: 'vybely-chat-app',
    storageBucket: 'vybely-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.vibely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6QplcgEeW0MyTfgdNl64V9I6VreL9gg',
    appId: '1:853841975905:ios:e064db5fa395292e4ae820',
    messagingSenderId: '853841975905',
    projectId: 'vybely-chat-app',
    storageBucket: 'vybely-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.vibely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd56RxMS8hJcLRFTefExF127lKuJDkVEc',
    appId: '1:853841975905:web:d5929d87fdb75f864ae820',
    messagingSenderId: '853841975905',
    projectId: 'vybely-chat-app',
    authDomain: 'vybely-chat-app.firebaseapp.com',
    storageBucket: 'vybely-chat-app.firebasestorage.app',
    measurementId: 'G-JRE3PX2NEB',
  );
}
